name: Run rclone tasks

# Controls when the action will run
on:
  push:
    # On which branches
    branches:
      - dev
  # On release
  release:
    types: [published]

# Variables
env:
  dest_path: '/public_html/wp-content/themes/hxl-wordpress-theme'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  rclone-dev:
    # Runner name
    runs-on: ubuntu-latest
    if: ${{ (github.event.release.target_commitish || github.ref_name) == 'dev' }}

    steps:
      # Checkout
      - uses: actions/checkout@v2

      # rclone
      - name: Copy files on dev
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_HDX_TYPE: ${{ secrets.RCLONE_CONFIG_HDX_TYPE }}
          RCLONE_CONFIG_HDX_HOST: ${{ secrets.RCLONE_CONFIG_HDX_HOST }}
          RCLONE_CONFIG_HDX_USER: ${{ secrets.RCLONE_CONFIG_HDX_USER_DEV }}
          RCLONE_CONFIG_HDX_PASS: ${{ secrets.RCLONE_CONFIG_HDX_PASS_DEV }}
        with:
          args: copy build HXL:${{ env.dest_path }}

  # Job name
  rclone-prod:
    # Runner name
    runs-on: ubuntu-latest
    if: ${{ (github.event.release.target_commitish || github.ref_name) == 'prod' }}

    steps:
      # Checkout
      - uses: actions/checkout@v2

      # rclone
      - name: Copy files on prod
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_HDX_TYPE: ${{ secrets.RCLONE_CONFIG_HDX_TYPE }}
          RCLONE_CONFIG_HDX_HOST: ${{ secrets.RCLONE_CONFIG_HDX_HOST }}
          RCLONE_CONFIG_HDX_USER: ${{ secrets.RCLONE_CONFIG_HDX_USER_PROD }}
          RCLONE_CONFIG_HDX_PASS: ${{ secrets.RCLONE_CONFIG_HDX_PASS_PROD }}
        with:
          args: copy build HXL:${{ env.dest_path }}